Adding additional test coverage for parsing
GoogleChrome/webidl-diff pull request #43
Opened 2017-05-15 21:43 UTC by m-cheung

2017-05-15 21:45 UTC, m-cheung commented
Please hold off on merging for now. It seems like there is still a bug with recognizing `serialize;`

Additionally, I noticed that the test harness may not be working as intended (I believe it may not be performing the checks correctly)

2017-05-16 12:12 UTC, mdittmer requested changes

2017-05-16 12:12 UTC, mdittmer commented on config/istanbul.yml
>      # TODO(markdittmer): Write tests to bump branch threshold up to 80%.
Please delete TODO as well.

2017-05-16 12:12 UTC, mdittmer commented on test/any/parsing/additional_idl_spec-helper.js
> +global.additional_idl_spec = `
nit: camelCase.

2017-05-16 12:12 UTC, mdittmer commented on test/any/parsing/cmp-integration.js
> +    'parse(spec) == parse(stringify(parse(spec)))',
More descriptive string?

2017-06-05 18:15 UTC, mdittmer approved these changes
LGTM

2017-06-05 19:01 UTC, merged