Changes to AST nodes for DAO usage
GoogleChrome/webidl-diff pull request #56
Opened 2017-06-26 20:05 UTC by m-cheung

2017-06-26 20:06 UTC, m-cheung commented on lib/org/chromium/webidl/Parser.js
> +          return parser.CallbackInterface.create({interfaceDetail: v});
Had to change this due to issue described below

2017-06-26 20:07 UTC, m-cheung commented on lib/org/chromium/webidl/ast/CallbackInterface.js
> +        return interfaceDetail.id;
`interface` cannot be used as a variable as we are running in strict mode and `interface` is a reserved word.
We could just do `ids: [ 'interface' ]` but I'm not certain if comparing interface objects would be efficient

2017-06-26 20:10 UTC, m-cheung commented on lib/org/chromium/webidl/ast/Implements.js
> +  ids: [ 'implementer', 'implemented' ],
This comment applies to all `ids` fields. Is there any performance concerns that we have to worry about? `implementer` and `implemented` are objects (with a `literal` property that is a string), and I'm not certain if the usage of objects as ID will be optimal.

2017-06-26 20:17 UTC, m-cheung commented on lib/org/chromium/webidl/ast/Named.js
> +  ids: ['name'],
`Operation` nodes implements `Named`, however, they have optional identifiers (as specified by the grammar). In these cases, `name === null` and issues may arise in the future with regards to this.

2017-06-27 14:12 UTC, mdittmer commented on lib/org/chromium/webidl/ast/Named.js
> +  ids: ['name'],
We should only need identity for top-level entities, right?

2017-06-27 20:28 UTC, mdittmer requested changes

2017-06-27 20:28 UTC, mdittmer commented on lib/org/chromium/webidl/ast/Definition.js
> +      factory: function() { return this.definition.id; },
Here, let's delegate to this.getName(), which delegates to definition.getName(), and so on. That way other AST nodes can implement getName(), without needing to have an id.

2017-06-27 20:28 UTC, mdittmer commented on lib/org/chromium/webidl/ast/Implements.js
> +  ids: [ 'implementer', 'implemented' ],
This is fine for now. Add a TODO that poses the question of whether we should have a custom id property that delegates to implementer and implemented's getName()

2017-06-27 20:28 UTC, mdittmer commented on lib/org/chromium/webidl/ast/Operation.js
> +      return this.name ? this.name.literal : null;
We shouldn't need this once we have getName on Named, right?

2017-06-27 21:43 UTC, m-cheung commented on lib/org/chromium/webidl/ast/Definition.js
> +      factory: function() { return this.definition.id; },
Not all definitions (maybe it is just `implements`) are named. Perhaps the `ids` field should be removed from `Implements` and replaced with `getName()` which returns those two objects?

2017-06-28 20:14 UTC, m-cheung commented
@mdittmer PTAL when you have the chance. I believe all requested changes have been made

2017-06-30 12:25 UTC, mdittmer approved these changes
LGTM. One last suggestion; please add TODO or implement defensive programming suggestion. Then, merge it!

2017-06-30 12:25 UTC, mdittmer commented on lib/org/chromium/webidl/ast/Named.js
> +      return this.name.literal;
If we want to be more defensive here, we could:

(1) Return `this.name ? this.name.literal || '' : ''`
(2) Implement `validate()` on `Definition` with a call to `this.SUPER()` and a `foam.assert()`ion that `id` is truthy
(3) Call `.validate()` before sending ASTs to a box or putting them to a DAO

2017-06-30 13:49 UTC, merged